name: DeployDev
on:
  push:
    branches:
      - develop
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Copy repository contents via scp
        uses: appleboy/scp-action@master
        env:
          HOST: ${{ secrets.HOST_LOMO }}
          USERNAME: ${{ secrets.USERNAME_LOMO }}
          PORT: ${{ secrets.PORT_LOMO }}
          KEY: ${{ secrets.SSHKEY_LOMO }}
        with:
          source: "."
          target: "/var/www/project-frontend/"
      - name: Executing remote command
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST_LOMO }}
          USERNAME: ${{ secrets.USERNAME_LOMO }}
          PORT: ${{ secrets.PORT_LOMO }}
          KEY: ${{ secrets.SSHKEY_LOMO }}
          script: cd /var/www/project-frontend/ && npm run docker-run-dev